// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  firebaseConfig : {
    
    // apiKey: "AIzaSyBw6ueeocfAhWM31ZK1feuQkwi0cDRpMhA",
    // authDomain: "bonvoy-f0f85.firebaseapp.com",
    // projectId: "bonvoy-f0f85",
    // storageBucket: "bonvoy-f0f85.appspot.com",
    // messagingSenderId: "529435904753",
    // appId: "1:529435904753:web:ae7c6a59069bae89c9f750",
    apiKey: "AIzaSyAdQ6MW1qvPjgEti01ytf5QiMLpJmY-u-Q",
    authDomain: "bonvoy-905c9.firebaseapp.com",
    projectId: "bonvoy-905c9",
    storageBucket: "bonvoy-905c9.appspot.com",
    messagingSenderId: "711267975994",
    appId: "1:711267975994:web:eb3eaa7fa086e5e9b68603",
    measurementId: "G-F1WHMJPBBH"
  
  },

  english_translations:{
    "Login_Account":"Login Account",
    "Mobile_Number":"Mobile Number",
    "Password":"Password",
    "Password_must_be_characters_or_more":"Password must be 8 characters or more.",
    "Login":"Login",
    "Get_OTP":"Get OTP",
    "Login_with_Mobile_Number":"Login with Mobile Number?",
    "Login_with_password":"Login with password?",
    "Verification":"Verification",
    "A_verification_code_has_been_sent_to":"A verification code has been sent to",
    "Edit_Number":"Edit Number",
    "Enter_your_OTP":"Enter your OTP",
    "Please_Enter_valid_OTP":"Please Enter Valid OTP",
    "Did_not_received_verification_code":"Did not received verification code?",
    "Resend_OTP":"Resend OTP",
    "This_field_is_required":"This field is required.",
    "Please_Select_valid_address":"Please Select correct address",
    "Enter_Valid_Number":"Enter correct Number",
    "Please_enter_valid_Email":"Please enter correct Email.",
    "Password_does_not_matched":"Password does not match.",
    "Registration_successfull_Welcome":"Registration successfull. Welcome ",
    "Product_added_to_wishlist":"Product added to wishlist",
    "Product_removed_from_wishlist":"Product removed from wishlist",
    "Item":"Item",
    "Items":"Items",
    "Profile_Updated_Successfully":"Profile Updated",
    "is_not_a_valid_file":"is not a valid file",
    "You_Have_Not_placed_any_orders_yet":"You Have Not placed any orders yet!",
    "Product_added_to_Cart":"Product added to Cart",
    "Update_Address":"Update Address",
    "Add_address":"Add Address",
    "Add_new_address":"Add New Address",
    "Home":"Home",
    "Office":"Office",
    "Other":"Other",
    "You_Have_Not_added_any_Address_yet":"You Have Not added any Address yet!",
    "Address_removed_successfully":"Address removed",
    "Address_added_Successfully":"Address added",
    "Address_updated_Successfully":"Address updated",
    "No_results_found":"No results found",
    "Your_Wishlist_is_empty":"Your wishlist is empty",
    "Cart":"Cart",
    "Your_cart_is_empty":"Your cart is empty",
    "Summary":"SUMMARY",
    "SUBTOTAL":"SUBTOTAL",
    "VAT":"TAX",
    "DELIVERY":"DELIVERY",
    "FREE":"FREE",
    "Shipping_Charges":"Shipping Charges",
    "HAVE_A_COUPON_CODE":"HAVE A COUPON CODE?",
    "Enter_Coupon_Code":"Enter Coupon Code",
    "Apply":"Apply",
    "Coupon_Applied":"Coupon Applied",
    "Remove":"Remove",
    "Total":"Total",
    "Checkout":"Checkout",
    "Please_Enter_Coupon_Code":"Please Enter Coupon Code",
    "Product_already_in_wishlist":"Product already in wishlist",
    "Select_card_design":"Select card design",
    "Card_Message":"Card Message",
    "To":"To",
    "From":"From",
    "Message":"Message",
    "Preview_card":"Preview card",
    "Select_add_ons":"Select additional prodcuts",
    "ADD":"ADD",
    "Card_Preview":"Card Preview",
    "Your_Message_Will_be_displayed_here":"Your Message Will be displayed here.",
    "Okay":"Okay",
    "Saved_Address":"Saved Address",
    "Send_to_new_address":"Send to new address",
    "Select_Date":"Select Date",
    "Today":"Today",
    "Tomorrow":"Tomorrow",
    "Select_Delivery_Time":"Select Delivery Time",
    "Pick_a_date":"Pick a date",
    "Add_Address":"Add Address",
    "Use_My_Location":"Use My Location",
    "Address_building_no":"Address (Building no. / Street)",
    "Full_Name":"Full Name",
    "Email_ID":"Email ID",
    "Address_Type":"Address Type",
    "Cancel":"Cancel",
    "No_result_found":"No result found!",
    "Geo_Code_failed_due_to":"We are unable to fetch your location at the moment. Please try again in sometime. ",
    "Error":"Error",
    "Select_payment_option":"Select payment option",
    "Credit_Debit_ATM_Card":"Credit / Debit / ATM Card",
    "PAY_NOW":"PAY NOW",
    "Wallet":"Wallet",
    "Available_Balance":"Available Balance :",
    "Cash_On_Delivery":"Cash On Delivery",
    "PLACE_ORDER":"PLACE ORDER",
    "Order_Placed_successfully":"Order Placed successfully!",
    "Details":"Details",
    "Address":"Address",
    "Payment":"Payment",
    "Continue":"Continue",
    "Flowers_Worth_a_thousand_words":"Flowers Worth a thousand words!",
    "Same_day_delivery_in_our_refrigerated_vans":"Same-day delivery in our refrigerated vans",
    "All_Flowers_are_arranged_in_our_workshop":"All Flowers are arranged in our workshop",
    "Quality_flowers_sourced_from_the_best_farms":"Quality flowers sourced from the best farms",
    "Shop_by_occasions":"Shop by occasions",
    "Shop_by_category":"Shop by category",
    "Best_Sellers":"Best Sellers",
    "ADD_TO_CART":"ADD TO CART",
    "Send_A_Subscription":"Send A Subscription",
    "Enjoy_Free_Delivery_And_Savings":"Enjoy Free Delivery And Savings Of 10% On Each Delivery",
    "EXPLORE_SUBSCRIPTION":"EXPLORE SUBSCRIPTION",
    "You_May_like":"You May like",
    "Sorry":"Sorry!",
    "CONTINUE_SHOPPING":"CONTINUE SHOPPING",
    "Your_payment_was_failed":"Your payment was failed.",
    "Your_payment_for_order_ID":"Your payment for order ID",
    "was_failed":"was failed.",
    "Thankyou":"Thank you!",
    "was_successfull":"was successfull.",
    "Your_order_has_been_placed":"Your order has been placed. We’ll notify you with the delivery information soon.",
    "Privacy_Policy":"Privacy Policy",
    "Where_flowers_bloom_So_does_hope":"“Where flowers bloom,  So does hope.”",
    "Category":"Category :",
    "Description":"Description",
    "Sorry_No_Product_found":"Sorry, No Product found!",
    "SIMILAR_PRODUCTS":"SIMILAR PRODUCTS",
    "FILTERS":"FILTERS",
    "Sort_By":"Sort By",
    "OCCASION":"OCCASION",
    "Price":"Price",
    "Color":"Color",
    "Show_Less":"Show Less",
    "More":"More",
    "Sorry_No_products_found":"Sorry,No products found!",
    "Load_More":"Load More",
    "Products":"Products",
    "Edit":"Edit",
    "Name":"Name",
    "Mobile_No":"Mobile No.",
    "Update_Profile":"Update Profile",
    "EDIT_DETAILS":"EDIT DETAILS",
    "ORDER_DETAILS":"ORDER DETAILS",
    "Order_ID":"Order ID :",
    "Order_NUMBER":"Order Number :",
    "Date":"Date :",
    "Order_date": "Order Date :",
    "Qty":"Qty.",
    "DELIVERY_ADDRESS":"DELIVERY ADDRESS",
    "DELIVERY_DETAILS":"DELIVERY DETAILS",
    "PAYMENT_METHOD":"PAYMENT METHOD",
    "Cash":"Cash",
    "Online":"Online",
    "STATUS":"STATUS",
    "CARD_MESSAGE":"CARD MESSAGE",
    "TO":"To :",
    "FROM":"From :",
    "MESSAGE":"Message :",
    "Discount":"Discount",
    "Discount_on_Bill":"Discount on Bill",
    "MY_ORDERS":"MY ORDERS",
    "REMINDERS":"REMINDERS",
    "Add_new_Reminder":"Add new Reminder",
    "Add Reminder":"Add Reminder",
    "Day":"Day",
    "Month":"Month",
    "Year":"Year",
    "ADD_REMINDER":"ADD REMINDER",
    "Enter_reminder_title":"Enter reminder title",
    "WALLET":"WALLET",
    "AVAILABLE_BALANCE":"Available Balance",
    "ADD_MONEY":"ADD MONEY",
    "Enter_amount":"Enter amount",
    "TRANSACTION":"TRANSACTION",
    "Credited_on":"Credited on",
    "Debited_on":"Debited on",
    "MOVE_TO_CART":"MOVE TO CART",
    "PROFILE":"PROFILE",
    "SAVED_ADDRESS":"SAVED ADDRESS",
    "WISHLIST":"WISHLIST",
    "REMINDER":"REMINDER",
    "Terms_and_Conditions":"Terms and Conditions",
    "MY_WISHLIST":"MY WISHLIST",
    "Our_Company":"Our Company",
    "About_us":"About us",
    "Careers":"Careers",
    "Our_services":"Our services",
    "FAQ":"FAQ",
    "Blogs":"Blogs",
    "Flower_Guides":"Flower Guides",
    "Help":"Help",
    "Customer_Support":"Customer Support",
    "Order_status":"Order status",
    "Terms_condition":"Terms & condition",
    "Copyright_Text":"Copyright @ 2023 Bonvoy | All rights reserved",
    "Ship_to":"Ship to :",
    "Login_Register":"Login/Register",
    "My_Account":"My Account",
    "My_Orders":"My Orders",
    "My_Addresses":"My Addresses",
    "My_Wishlist":"My Wishlist",
    "Logout":"Logout",
    "Search":"Search",
    "Help_Support":"Help & Support",
    "Orders":"Orders",
    "LOGIN_ACCOUNT":"LOGIN ACCOUNT",
    "SEND_OTP":"SEND Code",
    "LOGIN_WITH_OTP":"LOGIN WITH CODE",
    "LOGIN_WITH_PASSWORD":"LOGIN WITH PASSWORD",
    "Verify_OTP":"Verify Code",
    "Verify_Otp":"Verify Code",
    "Create_An_Account":"Create An Account",
    "Confirm_Password":"Confirm Password",
    "CREATE_ACCOUNT":"CREATE ACCOUNT",
    "Already_have_an_account":"Already have an account? ",
    "Login_successfull_Welcome":"Login successful.Welcome ",
    "You_are_not_registered_with_us":"You are not registered with us. Please Login with Mobile Number",
    "Invalid_OTP":"Invalid Code",
    "Something_went_wrong_Please_try_again_later":"Something went wrong.Please try again later!",
    "You_exceeded_OTP_request_max_attempt":"You exceeded maximum request attempts. Please try again after some time",
    "Logout_Successfully":"Logout Successful",
    "Contact_Us":"Contact Us",
    "Add_Gift_card":"Add Gift card",
    "Move_to_wishlist":"Move to wishlist",
    "reciever_phone":"Reciever's Mobile No.",
    "reciever_phone_number":"RECIEVER'S NO. :",
    "optional":"(optional)",
    "reciever_details":"Reciever's Details",
    "out_of_stock":"Out of Stock",
    "download_invoice":"Download Invoice",
    "I_agree_to_the":"I agree to the ",
    "Close":"Close",
    "terms":"Product may vary from the one displayed due to seasonal and market conditions.",
    "Please_accept_terms_and_conditions":"Please accept terms and conditions.",
    "available_on":"Available on :",
    "Delivery_is_only_inside_Riyadh":"Delivery in Riyadh only",
    "Latest":"Latest",
    "Recommended":"Recommended",
    "Low_price":"Low price",
    "High_price":"High price",
    "Popularity":"Popularity",
    "No_transactions_to_display":"No transactions to display.",
    "Reference":"Reference",
    "complete_your_order_now_and_earn":"Complete your order now & earn",
    "cashback_in_your_bloss_wallet":"cashback in your bloss wallet.",
    "We_would_love_to_hear_from_you_Please_find_the_details_to_contact_us_below":"We would love to hear from you. Please find the details to contact us below.",
    "CALL_US":"CALL US",
    "EMAIL_US":"EMAIL US",
    "FOLLOW_US":"FOLLOW US",
    "Or_drop_us_a_line":"Or drop us a line",
    "Send":"Send",
    "VIEW_ALL":"VIEW ALL",
    "OCATION":"SHOP BY OCATION",
    "Bloss_About":"Bloss is a Saudi brand Owned by Banan Arabia Trading Com",
    "Bloss_About2":"Specializing in roses and its products, serving its customers through several electronic channels",
    "OUR_APPLICATION":"OUR APPLICATION",
    "CONNECT_WITH_US":"Connect with us",
    "Buy_now":"Buy Now",
    "Billing_Addres": "Billing Address"






  },
  // arabic_translations:{
  //   "Login_Account":"تسجيل الدخول",
  //   "Mobile_Number":"رقم الجوال",
  //   "Password":"كلمة المرور",
  //   "Password_must_be_characters_or_more":"يجب أن تحتوي كلمة المرور على ثمانية أحرف (رموز) أو أكثر",
  //   "Login":"تسجيل الدخول",
  //   "Get_OTP":"احصل على رمز التحقق",
  //   "Login_with_Mobile_Number":"تسجيل الدخول عبر رقم الجوال",
  //   "Login_with_password":"تسجيل الدخول بإستخدام الرقم السري",
  //   "Verification":"التحقق",
  //   "A_verification_code_has_been_sent_to":"تم إرسال رمز التحقق إلى",
  //   "Edit_Number":"تعديل الرقم",
  //   "Enter_your_OTP":"أدخل رمز التحقيق",
  //   "Please_Enter_valid_OTP":"الرجاء إدخال رمز تحقيق صالح",
  //   "Did_not_received_verification_code":"لم احصل على رمز التحقيق؟",
  //   "Resend_OTP":"إعادة إرسال رمز التحقيق",
  //   "This_field_is_required":"خانة مطلوبة",
  //   "Please_Select_valid_address":"الرجاء إدخال عنوان صحيح",
  //   "Enter_Valid_Number":"أدخل الرقم الصحيح",
  //   "Please_enter_valid_Email":"الرجاء إدخال البريد الإلكتروني الصحيح",
  //   "Password_does_not_matched":"كلمة السر غير متطابقة",
  //   "Registration_successfull_Welcome":"تم التسجيل بنجاح. أهلا بك!",
  //   "Product_added_to_wishlist":"تمت إضافة المنتج إلى قائمة الرغبات (قائمتي الخاصة)",
  //   "Product_removed_from_wishlist":"تمت إزالة المنتج من قائمة الرغبات (قائمتي الخاصة)",
  //   "Item":"عنصر",
  //   "Items":"عناصر",
  //   "Profile_Updated_Successfully":"تحديث الملف الشخصي",
  //   "is_not_a_valid_file":"الملف غير صالح",
  //   "You_Have_Not_placed_any_orders_yet":"لا توجد طلبات حتى الآن ",
  //   "Product_added_to_Cart":"تمت إضافة المنتج إلى عربة التسوق",
  //   "Update_Address":"تحديث العنوان",
  //   "Add_address":"إضافة العنوان ",
  //   "Add_new_address":"إضافة عنوان جديد ",
  //   "Home":"الصفحة الرئيسية",
  //   "Office":"المكتب",
  //   "Other":"آخرى",
  //   "You_Have_Not_added_any_Address_yet":"لم تضف أي عنوان بعد!",
  //   "Address_removed_successfully":"إزالة العنوان",
  //   "Address_added_Successfully":"إضافة عنوان  ",
  //   "Address_updated_Successfully":"تحديث العنوان",
  //   "No_results_found":"لا توجد نتائج ",
  //   "Your_Wishlist_is_empty":"قائمة الرغبات فارغة",
  //   "Cart":"السلة",
  //   "Your_cart_is_empty":"السلة فارغة",
  //   "Summary":"ملخص / مختصر",
  //   "SUBTOTAL":"المبلغ الإجمالي",
  //   "VAT":"ضريبة القيمة المضافة (15٪)",
  //   "DELIVERY":"التوصيل ",
  //   "FREE":"مجاني",
  //   "Shipping_Charges":"رسوم الشحن",
  //   "HAVE_A_COUPON_CODE":"هل لديك رمز القسيمة؟",
  //   "Enter_Coupon_Code":"أدخل رمز القسيمة",
  //   "Apply":"تطبق / تطبيق",
  //   "Coupon_Applied":"تم تطبيق الكوبون",
  //   "Remove":"إزالة ",
  //   "Total":"المجموع",
  //   "Checkout":"الدفع",
  //   "Please_Enter_Coupon_Code":"الرجاء إدخال رمز القسيمة",
  //   "Product_already_in_wishlist":"المنتج موجود بالفعل في قائمة الرغبات (قائمتي الخاصة)",
  //   "Select_card_design":"حدد تصميم البطاقة",
  //   "Card_Message":"رسالة البطاقة",
  //   "To":"إلى",
  //   "From":"From",
  //   "Message":"الرسالة",
  //   "Preview_card":"معاينة البطاقة",
  //   "Select_add_ons":"إختر منتجات إضافية",
  //   "ADD":"إضافة",
  //   "Card_Preview":"معاينة البطاقة",
  //   "Your_Message_Will_be_displayed_here":"سيتم عرض رسالتك هنا",
  //   "Okay":"حسنًا / صحيح!",
  //   "Saved_Address":"حفظ العنوان",
  //   "Send_to_new_address":"الإرسال إلى عنوان آخر",
  //   "Select_Date":"حدد تاريخ الإسال",
  //   "Today":"اليوم",
  //   "Tomorrow":"غداً",
  //   "Select_Delivery_Time":"أدخل موعد الوصول",
  //   "Pick_a_date":"أختر التاريخ",
  //   "Add_Address":"إضافة عنوان ",
  //   "Use_My_Location":"أختر موقعي",
  //   "Address_building_no":"العنوان (رقم المبنى / الشارع)",
  //   "Full_Name":"الإسم الكامل",
  //   "Email_ID":"الإيميل الإلكتروني",
  //   "Address_Type":"نوع العنوان",
  //   "Cancel":"إلغاء",
  //   "No_result_found":"لم يتم العثور على نتائج!",
  //   "Geo_Code_failed_due_to":"لا يمكننا العثور على موقعك في الوقت الحالي. يرجى المحاولة مرة أخرى في وقت ما.",
  //   "Error":"خطأ",
  //   "Select_payment_option":"حدد خيار الدفع",
  //   "Credit_Debit_ATM_Card":"بطاقة الائتمان / الخصم / الصراف الآلي (مدى - فيزا - أبل باي - كاش)",
  //   "PAY_NOW":"أدفع الآن",
  //   "Wallet":"المحفظة",
  //   "Available_Balance":"الرصيد المتوفر :",
  //   "Cash_On_Delivery":"الدفع عند الاستلام",
  //   "PLACE_ORDER":"تقديم طلب شراء / تقديم الطلب",
  //   "Order_Placed_successfully":"تم تسجيل الطلب بنجاح!",
  //   "Details":"تفاصيل",
  //   "Address":"عنوان ",
  //   "Payment":"الدفع",
  //   "Continue":"الاستمرار",
  //   "Flowers_Worth_a_thousand_words":"زهور تساوي ألف كلمة!",
  //   "Same_day_delivery_in_our_refrigerated_vans":"التوصيل في نفس اليوم في شاحناتنا المبردة",
  //   "All_Flowers_are_arranged_in_our_workshop":"يتم تنسيق جميع الورود والهدايا في معملنا الخاص",
  //   "Quality_flowers_sourced_from_the_best_farms":"زهور عالية الجودة من أفضل البساتين",
  //   "Shop_by_occasions":"تسوق حسب المناسبات",
  //   "Shop_by_category":"تسوق حسب القسم",
  //   "Best_Sellers":"الأفضل مبيعًا",
  //   "ADD_TO_CART":"إضافة إلى السلة",
  //   "Send_A_Subscription":"إرسال إشتراك ",
  //   "Enjoy_Free_Delivery_And_Savings":"تمتع بالتوصيل المجاني مع توفير 10٪ على كل عملية توصيل",
  //   "EXPLORE_SUBSCRIPTION":"تعرف على الاشتراك",
  //   "You_May_like":"قد يعجبك",
  //   "Sorry":"نأسف!",
  //   "CONTINUE_SHOPPING":"أكمل التسوق",
  //   "Your_payment_was_failed":"فشلت عميلة الدفع",
  //   "Your_payment_for_order_ID":"الرقم الخاص بعميلة الدفع",
  //   "was_failed":"فشلت المحاولة",
  //   "Thankyou":"شكراً لك!",
  //   "was_successfull":"تمت بنجاح!",
  //   "Your_order_has_been_placed":"تم إعتماد الطلب. سيتم إبلاغكم بمعلومات التسليم قريبًا.",
  //   "Privacy_Policy":"سياسة الخصوصية",
  //   "Where_flowers_bloom_So_does_hope":"اينما تزهر الورود يُبعث الأمل",
  //   "Category":"فئة:",
  //   "Description":"الوصف:",
  //   "Sorry_No_Product_found":"عذرا ، لم يتم العثور على المنتج !",
  //   "SIMILAR_PRODUCTS":"منتجات مماثلة",
  //   "FILTERS":"تصفية",
  //   "Sort_By":"صنف حسب",
  //   "OCCASION":"مناسبات",
  //   "Price":"الأسعار",
  //   "Color":"الألوان ",
  //   "Show_Less":"أقل..",
  //   "More":"أكثر..",
  //   "Sorry_No_products_found":" عذرا ، لم يتم العثور على منتجات !",
  //   "Load_More":"تحميل المزيد",
  //   "Products":"المنتجات",
  //   "Edit":"تحرير",
  //   "Name":"الأسم",
  //   "Mobile_No":"رقم الجوال ",
  //   "Update_Profile":"تحديث الملف",
  //   "EDIT_DETAILS":"تحرير التفاصيل",
  //   "ORDER_DETAILS":"تفاصيل الطلب",
  //   "Order_ID":"رقم الطلب:",
  //   "Order_NUMBER":"رقم الطلب:",

  //   "Date":"التاريخ:",
  //   "Qty":"الكمية",
  //   "DELIVERY_ADDRESS":"عنوان التسليم",
  //   "DELIVERY_DETAILS":"تفاصيل التسليم",
  //   "PAYMENT_METHOD":"طريقة الدفع او السداد",
  //   "Cash":"نقداً",
  //   "Online":"عبر الانترنت",
  //   "STATUS":"الحالة",
  //   "CARD_MESSAGE":"رسالة البطاقة",
  //   "TO":"إلى:",
  //   "FROM":"From :",
  //   "MESSAGE":"الرسالة :",
  //   "Discount":"خصم",
  //   "Discount_on_Bill":"خصم على الفاتورة",
  //   "MY_ORDERS":"طلباتي",
  //   "REMINDERS":"تذكير",
  //   "Add_new_Reminder":"إضافة تذكير جديد",
  //   "Add Reminder":"إضافة تذكير",
  //   "Day":"اليوم",
  //   "Month":"الشهر",
  //   "Year":"السنة",
  //   "ADD_REMINDER":"إضافة تذكير",
  //   "Enter_reminder_title":"أدخل عنوان التذكير",
  //   "WALLET":"المحفظة",
  //   "AVAILABLE_BALANCE":"الرصيد المتوفر",
  //   "ADD_MONEY":"إضافة المال",
  //   "Enter_amount":"أدخل المبلغ أو الكمية",
  //   "TRANSACTION":"المعاملات",
  //   "Credited_on":"الاعتماد في",
  //   "Debited_on":"خصم من ",
  //   "MOVE_TO_CART":"إنتقل إلى العربة",
  //   "PROFILE":"الملف الشخصي",
  //   "SAVED_ADDRESS":"العنوان المحفوظ",
  //   "WISHLIST":"قائمة الرغبات ",
  //   "REMINDER":"تذكير",
  //   "Terms_and_Conditions":"الأحكام والشروط",
  //   "MY_WISHLIST":"قائمة رغباتي",
  //   "Our_Company":"شركتنا ",
  //   "About_us":"من نحن",
  //   "Careers":"وظائف",
  //   "Our_services":"خدماتنا",
  //   "FAQ":"الأسئلة الشائعة",
  //   "Blogs":"المدونات",
  //   "Flower_Guides":"دليل الزهور",
  //   "Help":"مساعدة",
  //   "Customer_Support":"خدمات العملاء",
  //   "Order_status":"حالة الطلب",
  //   "Terms_condition":"الشروط والأحكام",
  //   "Copyright_Text":"حقوق النشر @ 2022 Bloss | كل الحقوق محفوظة",
  //   "Ship_to":"إرسال إلى:",
  //   "Login_Register":"دخول/ تسجيل",
  //   "My_Account":"حسابي",
  //   "My_Orders":"طلباتي",
  //   "My_Addresses":"عنواني",
  //   "My_Wishlist":"قائمة رغباتي",
  //   "Logout":"تسجيل خروج",
  //   "Search":"البحث",
  //   "Help_Support":"المساعدة والدعم الفني",
  //   "Orders":"الطلبات",
  //   "LOGIN_ACCOUNT":"تسجيل الدخول",
  //   "SEND_OTP":"أرسل رمز التأكيد",
  //   "LOGIN_WITH_OTP":"تسجيل الدخول باستخدام الرمز",
  //   "LOGIN_WITH_PASSWORD":"تسجيل الدخول بكلمة المرور",
  //   "Verify_OTP":"رمز التأكيد",
  //   "Verify_Otp":"رمز التأكيد",
  //   "Create_An_Account":"إنشاء حساب",
  //   "Confirm_Password":"تأكيد كلمة المرور",
  //   "CREATE_ACCOUNT":"إنشاء حساب",
  //   "Already_have_an_account":"هل لديك حساب؟ ",
  //   "Login_successfull_Welcome":"تم تسجيل الدخول بنجاح!",
  //   "You_are_not_registered_with_us":"أنت غير مسجل معنا. الرجاء تسجيل الدخول باستخدام رقم الجوال",
  //   "Invalid_OTP":"الرمز غير صالح",
  //   "Something_went_wrong_Please_try_again_later":"حدث خطأ، يرجى المحاولة فى وقت لاحق!",
  //   "You_exceeded_OTP_request_max_attempt":"لقد تجاوزت الحد الأقصى من محاولات الطلب. من فضلك حاول مرة أخرى في وقت لاحق",
  //   "Logout_Successfully":"نجح تسجيل الخروج",
  //   "Contact_Us":"تواصل معنا",
  //   "Add_Gift_card":"أضف بطاقة هدية",
  //   "Move_to_wishlist":"انقل الى المفضلة",
  //   "reciever_phone":"رقم جوال المستلم",
  //   "reciever_phone_number":"رقم جوال المستلم :",
  //   "optional":"(اختياري)",
  //   "reciever_details":"بيانات المستلم",
  //   "out_of_stock":"إنتهى من المخزن",
  //   "download_invoice":"تحميل الفاتورة",
  //   "I_agree_to_the":"أوافق على ",
  //   "Close":"إغلاق",
  //   "terms":"المنتجات المعروضة في الصور قد تختلف اختلاف بسيط وذلك حسب عوامل الطلب الموسمية.",
  //   "Please_accept_terms_and_conditions":"الموافقة على الشروط والأحكام",
  //   "available_on":"متاح في",
  //   "Delivery_is_only_inside_Riyadh":"التوصيل متاح فقط داخل مدينة الرياض",
  //   "Latest":"الأحدث",
  //   "Recommended":"المقترحات",
  //   "Low_price":"الأقل سعراً",
  //   "High_price":"الأعلى سعراً",
  //   "Popularity":"الأكثر مبيعاً",
  //   "No_transactions_to_display":"لا توجد معاملات لعرضها.",
  //   "Reference":"مرجع",
  //   "complete_your_order_now_and_earn":"أكمل طلبك الآن واكسب",
  //   "cashback_in_your_bloss_wallet":"استرداد نقدي في محفظة Bloss الخاصة بك.",
  //   "We_would_love_to_hear_from_you_Please_find_the_details_to_contact_us_below":"We would love to hear from you. Please find the details to contact us below.",
  //   "CALL_US":"للاتصال",
  //   "EMAIL_US":"راسلنا عبر البريد الالكتروني",
  //   "FOLLOW_US":"تابعنا",
  //   "Or_drop_us_a_line":"أو ارسل لنا رسالة",
  //   "Send":"ارسال",
  //   "VIEW_ALL":"مشاهدة الكل",
  //   "OCATION":"SHOP BY OCATION",
  //   "Bloss_About":"بلوس علامة تجارية سعودية مملوكة لشركة بنان العربية للتجارة." ,
  //   "Bloss_About2":"متخصصة في الورد ومنتجاته ، تخدم عملائها من خلال عدت قنوات",
  //   "OUR_APPLICATION":"تطبيقنا",
  //   "CONNECT_WITH_US":"تواصل معنا"

  // }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
