export interface address_data {
    id?:string,
    full_name: string,
    address: string,
    email_id: string,
    latitude: string,
    longitude: string,
    type: string,
    phone: string,
    country_code: string,
    pincode: string,
    landmark: string,
    address_type: string,
    country_id: string,
    city_id: string,
    state_id: string,
    action: string,
    load?:boolean,
}